package org.grails.datastore.gorm.sparql.mapping.config

import org.grails.datastore.mapping.config.Entity
import org.openrdf.model.IRI
import org.openrdf.model.vocabulary.RDF

/**
 * Is used to access the mapping-configuration from a Domain Class
 *
 * Created by mwildt on 30.06.16.
 */
class SparqlMappingEntity extends Entity {

    /*
     * the predicate used to specify the semantic type
     */
    def IRI predicate = RDF.TYPE

    /*
     * the object value to specifiy the type this is generated by Default
     * by using the classname
     */
    def IRI object = null

}
